Update 20-02-2026 (Lunar Jan 04 2026)
- Add gitignore .swp (vim);
- Add elpy, remove unnecessary mode (emacs);
- Remove user hardcode: bashrc, zshrc, kitty;
- Rofi clipboard display in bottom right instead centering;
- Add some line in function file

diff --git a/function b/function
--- a/function
+++ b/function
@@ -18,7 +18,8 @@ prepare(){
     mkdir -p "${HOME}/.local/bin" "${HOME}/repos"
     cp "${HOME}/.bashrc" "${HOME}/.bashrc.bak-$(date +%H.%M.%S.%s-%d.%m.%Y)"
     cp $WORKDIR/pref/exportrc $HOME/.exportrc
-    #PDISPLAY=$(xrandr | grep ' connected' | awk '{ print $1 }' | head -n1)
+    mkdir $HOME/.dev
+    # PDISPLAY=$(xrandr | grep ' connected' | awk '{ print $1 }' | head -n1)
 }
 
 tsoding_update(){
@@ -27,7 +28,7 @@ tsoding_update(){
         git -C tsoding pull --recurse-submodules && \
         git -C tsoding submodule update --init --recursive
     ) || \
-        git clone --recurse-submodules https://github.com/rexim/dotfiles.git tsoding 2>/dev/null 
+        git clone --recurse-submodules https://github.com/rexim/dotfiles.git tsoding 2>/dev/null
 
 sed -i "/gitconfig/d" ${WORKDIR}/tsoding/MANIFEST
 bash ${WORKDIR}/tsoding/deploy.sh  MANIFEST
@@ -136,7 +137,7 @@ cat > ${HOME}/.run-web.sh <<'EOF'
 urls = ( $url  )
 for url in "${urls[@]}"; do
     /bin/google-chrome-stable "$url" &
-done 
+done
 EOF
 
 cat > ${HOME}/.welcome <<'EOF'
@@ -164,13 +165,17 @@ fi
 
 emacsrun () {
     # go install golang.org/x/tools/gopls@latest
-    cat > ~/.local/bin/emacsscript.sh <<'EOF'
+    mkdir -p $HOME/.local/bin
+    EMACS_PATH="$HOME/.local/bin/emacsscript.sh"
+    cat > $EMACS_PATH <<'EOF'
 #!/bin/env bash
 
 (emacsclient -e "(emacs-pid)" >/dev/null 2>&1 || emacs --daemon) && exec emacsclient -t "$@"
 EOF
-    
-chmod +x ~/.local/bin/emacsscript.sh
+
+    chmod +x $EMACS_PATH
+    ln -sf $EMACS_PATH $HOME/.local/bin/e
+    ln -sf $EMACS_PATH $HOME/.local/bin/emacs
 }
 
 
@@ -193,15 +198,15 @@ if ! exist "betterlockscreen"; then
     for i in autoconf gcc make pkg-config libpam0g-dev libcairo2-dev libfontconfig1-dev \
     libxcb-composite0-dev libev-dev libx11-xcb-dev libxcb-xkb-dev libxcb-xinerama0-dev libxcb-randr0-dev \
     libxcb-image0-dev libxcb-util0-dev libxcb-xrm-dev libxkbcommon-dev \
-    libxkbcommon-x11-dev libjpeg-dev libgif-dev imagemagick bc; do 
-    
-    if ! dpkg -l "$i" > /dev/null 2>&1; then 
-        ERRI+="$i " 
+    libxkbcommon-x11-dev libjpeg-dev libgif-dev imagemagick bc; do
+
+    if ! dpkg -l "$i" > /dev/null 2>&1; then
+        ERRI+="$i "
     fi
 done
 
-if [[ -n $ERRI ]]; then 
-    echo -e "Required packages for i3lock-color: \e[31m$ERRI \e[0m" 
+if [[ -n $ERRI ]]; then
+    echo -e "Required packages for i3lock-color: \e[31m$ERRI \e[0m"
     exit 127
 fi
   # git clone https://github.com/Raymo111/i3lock-color.git
